Pepper\Rule\TooManyMethods: Class {name} has too many methods.
Pepper\Rule\MethodTooLong: Method {name} is too long on line {line}.
Pepper\Rule\UnnecessaryIf: Unnecessary if statement on line {line}.
Pepper\Rule\GlobalVariable: Use of global variable on line {line}.
Pepper\Rule\UndefinedVariable: Undefined variable {name} used on line {line}.
Pepper\Rule\DoubleEquals: Use of double equals statement on line {line}.
Pepper\Rule\UnnecessaryElse: Unecessary else statement used on line {line}.
Pepper\Rule\NestingTooDeep: Nesting too deep on line {line}.
